name: CI
on: 
    push:
        branches:
            - main
        paths-ignore:
            - '**.md'
    pull_request:
        paths-ignore:
            - '**.md'
jobs:
    tests:
        name: Tests
        runs-on: macOS-latest
        steps:
            - uses: actions/checkout@v2

            # Setup Java
            - name: Set up JDK
              uses: actions/setup-java@v4
              with:
                distribution: 'zulu'
                java-version: '17'
                java-package: jdk

            # Validate the Gradle wrapper JAR files.
            - name: Validate Gradle Wrapper
              uses: gradle/wrapper-validation-action@v1

            # Clean gradle cache to stay within github's cache size limits
            - name: Clean Gradle Cache
              run: rm -rf ~/.gradle/caches

            # Restore the cache
            - uses: actions/cache@v1
              with:
                  path: ~/.gradle/caches
                  key: gradle-${{ runner.os }}-${{ hashFiles('**/build.gradle') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}

            - name: Spotless
              run: ./gradlew spotlessCheck

            - name: Unit Tests
              timeout-minutes: 10
              run: ./gradlew testDebugUnitTest